# Stage 1: Build the application
FROM node:18-alpine AS build

# Set the working directory inside the container
WORKDIR /frontend

# Copy only the package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy all frontend files to the container
COPY . .

# Build the React project
RUN npm run build

# List the contents of the dist directory for debugging
RUN ls -la /frontend/dist

# Stage 2: Serve the application using Nginx
FROM nginx:alpine AS production

# Copy the build output from the previous stage
COPY --from=build /frontend/dist /usr/share/nginx/html


COPY /home/ubuntu/mycert/mywebsite.crt /etc/ssl/certs/mywebsite.crt
COPY /home/ubuntu/mycert/mywebsite.key /etc/ssl/private/mywebsite.key

# Copy a custom Nginx configuration file (if needed)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Fix permissions for Nginx
RUN chown -R nginx:nginx /usr/share/nginx/html

# Expose the port Nginx is running on
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]