# version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend_chat_app
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - ./backend:/backend
    # env_file:
    #   - .env
    expose:
      - 8000  
    ports:
      - "8000:8000" 

  frontend:
    build:
      context: ./frontend
    container_name: frontend_chat_app
    volumes:
      - ./frontend/dist:/usr/share/nginx/html

  nginx:
    image: nginx:alpine
    container_name: nginx_chat_app

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html  
    ports:
      - "8080:80"  
    depends_on:
      - backend
      - frontend