# backend/Dockerfile
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /backend

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

RUN python manage.py migrate --noinput

RUN python manage.py createsuperuser --noinput

# Gunicorn command
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application"]
